name: "Github Actions Demo"
run-name: ${{github.actor}} is testing ${{github.repository}}
on: [push]
jobs:
    Build-Node-App-Action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - run: yarn
            - run: yarn start

                