name: "Github Actions Demo"

on: [push]

jobs:
    Build-Node-App-Action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22.3'

            - name: Create .env file
              run: |
                echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
                echo "API_VAR=${{ vars.API_VAR }}" >> .env

            - name: Verify .env file
              run: cat .env

                