name: "Github Actions Demo"

on: [push]

env:
    API_SECRET: ${{ secrets.API_SECRET }}
    API_VAR: ${{ vars.API_VAR }}

jobs:
    Build-Node-App-Action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                echo "API_SECRET=$API_SECRET" >> .env
                echo "API_VAR=$API_VAR" >> .env

            - name: Verify .env file
              run: cat .env

                